### ISSUE TITLE
Add focus effect on buttons.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#1049] opened 2023-02-07 17:11 UTC
https://app.zeplin.io/project/62b9dba49dd2b211410e608e/screen/635c072bf964ca340b364a15

**Comment by sandeep-ps** [comment] 2023-02-22 15:24
Bing initially did the work in #1053, but later another feature, #1048, was merged first, and it had the necessary changes. Closing this issue as a duplicate.

**Closed by sandeep-ps** 2023-02-22 15:24 UTC

**Comment by sandeep-ps** [comment] 2023-02-22 15:54
Duplicate of https://github.com/rokwire/events-manager/issues/1048
