### ISSUE TITLE
Add disable effect on buttons.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#1050] opened 2023-02-07 17:11 UTC
https://app.zeplin.io/project/62b9dba49dd2b211410e608e/screen/635c072bf964ca340b364a15
https://user-images.githubusercontent.com/5349154/217023556-d1fd1e04-8eee-4074-bb62-ad803ef86d52.png

**Comment by sandeep-ps** [comment] 2023-02-22 15:25
Bing initially did the work in #1052, but later another feature, #1048, was merged first and had the necessary changes. Closing this issue as a duplicate.

**Closed by sandeep-ps** 2023-02-22 15:25 UTC

**Comment by sandeep-ps** [comment] 2023-02-22 15:52
Duplicate of #1048.
